var textos_ES = {

	// General titles
	'text_titulo_app': 'Interfaz ET2 IU',
	'text_titulo_menu': 'Opciones Menu',
	'text_titulo_pie': 'Pie de pagina',
	'text_article': 'Seccion article',
	'label_seleccioncolumnas': 'Seleccionar columnas',

	// Menu
	'text_menu_persona': 'Gestionar persona',

	// Persona page titles
	'text_titulo_page_persona' : 'Gestion de Datos Personales',
	'text_contenido_titulo_form_persona_ADD': 'Formulario Alta Datos Personales',
	'text_contenido_titulo_form_persona_EDIT': 'Formulario Modificacion Datos Personales',
	'text_contenido_titulo_form_persona_DELETE': 'Formulario Eliminacion Datos Personales',
	'text_contenido_titulo_form_persona_SHOWCURRENT': 'Formulario Detalle Datos Persona',
	'text_contenido_titulo_form_persona_SEARCH': 'Formulario Busqueda Datos Persona',

	// Attributes (labels)
	'dni': 'Identificacion',
	'nombre_persona': 'Nombre',
	'apellidos_persona': 'Apellidos',
	'fechaNacimiento_persona': 'Fecha Nacimiento',
	'direccion_persona': 'Direccion',
	'telefono_persona': 'Telefono',
	'email_persona': 'Correo Electronico',
	'foto_persona': 'Foto',

	'label_dni': 'Identificacion',
	'label_nombre_persona': 'Nombre',
	'label_apellidos_persona': 'Apellidos',
	'label_fechaNacimiento_persona': 'Fecha Nacimiento',
	'label_direccion_persona': 'Direccion',
	'label_telefono_persona': 'Telefono',
	'label_email_persona': 'Correo Electronico',
	'label_foto_persona': 'Foto',
	'label_nuevo_foto_persona': 'Nueva Foto',

	// Validation errors (Spanish, ASCII)
	'dni_min_size_KO':'Dni demasiado corto. Debe tener 8 numeros y 1 caracter alfabetico',
	'dni_max_size_KO':'DNI demasiado largo. Debe tener 8 numeros y 1 caracter alfabetico',
	'dni_format_KO':'Formato dni/nie no correcto. DNI 8digitos1letra, NIE 1letra7digitos1letra',

	'nombre_persona_min_size_KO':'Nombre demasiado corto. Debe tener mas de 4 caracteres alfabeticos',
	'nombre_persona_max_size_KO':'Nombre demasiado largo. Debe tener menos de 15 caracteres alfabeticos',
	'nombre_persona_format_KO':'Nombre no correcto. Solo se permiten alfabeticos',

	'apellidos_persona_min_size_KO': 'Apellidos demasiado corto. Debe tener mas de 4 caracteres alfabeticos o espacios',
	'apellidos_persona_max_size_KO': 'Apellidos demasiado largo. Debe tener menos de 20 caracteres alfabeticos o espacios',
	'apellidos_persona_format_KO': 'Apellidos no correcto. Solo se permiten alfabeticos y espacios',

	'fechaNacimiento_persona_format_KO': 'Fecha no correcta. Debe tener el formato dd/mm/aaaa',
	'fechaNacimiento_persona_valid_KO': 'Fecha no valida. La fecha debe existir',

	'email_persona_min_size_KO': 'El tamano debe ser de minimo 5',
	'email_persona_max_size_KO':'El tamano debe ser de maximo 50',
	'email_persona_format_KO':'El correo electronico debe tener un formato valido',

	'nuevo_foto_persona_not_exist_file_KO':'El fichero no existe. Debe subir una foto',
	'nuevo_foto_persona_max_size_file_KO':'El tamano del fichero excede el maximo permitido',
	'nuevo_foto_persona_type_file_KO':'Tipo de fichero no permitido (debe ser image/jpeg)',
	'nuevo_foto_persona_format_name_file_KO':'Nombre de fichero invalido',
	'nuevo_foto_persona_min_size_KO':'El fichero esta vacio',
	'nuevo_foto_persona_max_size_KO':'El tamano del fichero excede el maximo permitido',

	'foto_persona_max_size_KO':'El tamano del fichero excede el maximo permitido',
	'foto_persona_format_KO':'Formato de fichero no valido',

	'RECORDSET_VACIO' : 'No hay coincidencias para la busqueda',
	'dni_es_nulo_KO':'El dni no puede ser vacio',

	'admin_no_se_puede_modificar_KO':'El admin no se puede modificar',

	// ET2 keys (Spanish)
	'msg_exito': 'Exito',
	'msg_campo_opcional': 'Campo opcional',
	'msg_se_permite_busqueda_vacia': 'Se permite busqueda vacia',
	'msg_se_encuentra_el_usuario_por_login_exacto': 'Se encuentra el usuario por login exacto',
	'msg_se_encuentra_el_usuario_por_email_exacto': 'Se encuentra el usuario por email exacto',
	'msg_se_encuentra_el_usuario_por_telefono_exacto': 'Se encuentra el usuario por telefono exacto',
	'msg_se_encuentra_el_usuario_por_dni_exacto': 'Se encuentra el usuario por DNI exacto',
	'msg_se_encuentran_usuarios_por_coincidencia_parcial': 'Se encuentran usuarios por coincidencia parcial',
	'msg_se_encuentran_fotos_por_coincidencia_parcial': 'Se encuentran fotos por coincidencia parcial',
	'msg_se_encuentra_la_foto_por_nombre_exacto': 'Se encuentra la foto por nombre exacto',
	'msg_se_encuentra_usuario_por_titulacion_valida': 'Se encuentra usuario por titulacion valida',

	// Articulo
	'CodigoA_negative_KO': 'El codigo debe ser entero positivo',
	'CodigoA_not_numeric_KO': 'El codigo debe ser numerico',
	'AutoresA_maxlen_KO': 'Maximo 200 caracteres',
	'TituloA_empty_KO': 'El titulo no puede estar vacio',
	'TituloA_maxlen_KO': 'Maximo 100 caracteres',
	'TituloR_maxlen_KO': 'Maximo 100 caracteres',
	'ISSN_format_KO': 'Formato ISSN invalido (ej. 1234-567X)',
	'PagIniA_negative_KO': 'Debe ser entero >= 0',
	'PagFinA_invalid_range_KO': 'PagFinA debe ser >= PagIniA',
	'FechaPublicacionR_format_KO': 'Formato fecha YYYY-MM-DD',
	'FicheropdfA_empty_KO': 'El fichero no puede estar vacio',
	'FicheropdfA_type_KO': 'Solo se permiten ficheros .pdf',
	'FicheropdfA_no_extension_KO': 'Debe incluir extension valida',
	'FicheropdfA_name_KO': 'Formato nombre invalido (no permite espacios ni caracteres especiales)',
	'FicheropdfA_size_KO': 'Tamano maximo 5242880 bytes',
	'EstadoA_invalid_KO': 'Estado no permitido',
	'VolumenR_maxlen_KO': 'Maximo 4 caracteres',

	// Alumnograduacion (Spanish)
	'alumnograduacion_login': 'Login',
	'alumnograduacion_password': 'Contrasena',
	'alumnograduacion_password_accented_KO': 'Solo puede contener caracteres alfabeticos sin acentos',
	'alumnograduacion_nombre': 'Nombre',
	'alumnograduacion_apellidos': 'Apellidos',
	'alumnograduacion_titulacion': 'Titulacion',
	'alumnograduacion_titulacion_valid_KO': 'Debe seleccionar una opcion valida',
	'alumnograduacion_dni': 'DNI',
	'alumnograduacion_dni_letter_KO': 'Formato nif o nie incorrecto, letra y numero no se corresponden',
	'alumnograduacion_telefono': 'Telefono',
	'alumnograduacion_email': 'Correo electronico',
	'alumnograduacion_direccion': 'Direccion',
	'alumnograduacion_direccion_alpha_KO': 'Solo puede contener caracteres alfanumericos con acentos y espacios',
	'alumnograduacion_email_empty_KO': 'El campo correo electronico no puede estar vacio',
	'alumnograduacion_email_characters_KO': 'Solo puede contener caracteres alfabeticos, numeros, signos de puntuacion y espacios en blanco',
	'alumnograduacion_password_empty_KO': 'El campo no puede contener solo espacios',
	'alumnograduacion_password_num_KO': 'Solo puede contener caracteres alfabeticos',
	'alumnograduacion_password_symbols_KO': 'Solo puede contener caracteres alfabeticos',
	'alumnograduacion_nombre_num_KO': 'Solo puede contener caracteres alfabeticos',
	'alumnograduacion_nombre_symbols_KO': 'Solo puede contener caracteres alfabeticos',
	'alumnograduacion_apellidos_only_spaces_KO': 'No puede contener solo espacios',
	'alumnograduacion_apellidos_num_KO': 'Solo puede contener caracteres alfabeticos',
	'alumnograduacion_apellidos_symbols_KO': 'Solo puede contener caracteres alfabeticos',
	'alumnograduacion_titulacion_empty_KO': 'Debe seleccionar una titulacion',
	'alumnograduacion_dni_numbers_KO': 'Falta la letra',
	'alumnograduacion_telefono_spaces_KO': 'No puede contener espacios',
	'alumnograduacion_telefono_dashes_KO': 'No puede contener guiones',
	'alumnograduacion_direccion_only_spaces_KO': 'No puede contener solo espacios',
	'alumnograduacion_fotoacto': 'Foto acta',
	'alumnograduacion_login_not_alphabetic_KO': 'Solo puede contener caracteres alfabeticos',
	'alumnograduacion_login_has_accents_KO': 'Solo puede contener caracteres alfabeticos sin acentos',
	'alumnograduacion_password_too_short_KO': 'El campo no puede tener una longitud menor a 8 caracteres',
	'alumnograduacion_password_too_long_KO': 'El tamano debe ser de maximo 64 caracteres',
	'alumnograduacion_password_not_alphabetic_KO': 'Solo puede contener caracteres alfabeticos',
	'alumnograduacion_password_has_accents_KO': 'Solo puede contener caracteres alfabeticos sin acentos',
	'alumnograduacion_nombre_too_short_KO': 'El tamano debe ser de minimo 2',
	'alumnograduacion_nombre_too_long_KO': 'El tamano debe ser de maximo 25',
	'alumnograduacion_apellidos_not_alphabetic_KO': 'Solo puede contener caracteres alfabeticos',
	'alumnograduacion_apellidos_too_short_KO': 'El tamano debe ser de minimo 2',
	'alumnograduacion_apellidos_too_long_KO': 'El tamano debe ser de maximo 35',
	'alumnograduacion_titulacion_invalid_KO': 'Titulacion invalida',
	'alumnograduacion_dni_invalid_length_KO': 'Longitud DNI incorrecta',
	'alumnograduacion_dni_not_numeric_KO': 'DNI debe ser numerico',
	'alumnograduacion_dni_invalid_letter_KO': 'Letra DNI invalida',
	'alumnograduacion_telefono_invalid_length_KO': 'Longitud telefono incorrecta',
	'alumnograduacion_telefono_not_numeric_KO': 'Telefono debe ser numerico',
	'alumnograduacion_email_too_long_KO': 'El tamano debe ser de maximo 100',
	'alumnograduacion_direccion_too_short_KO': 'El campo no puede estar vacio',
	'alumnograduacion_direccion_not_alphanumeric_KO': 'Formato de direccion no valido',
	'alumnograduacion_email_too_short_KO': 'El tamano debe ser de minimo 5',
	'alumnograduacion_email_invalid_format_KO': 'El correo electronico debe tener un formato valido',
	'alumnograduacion_email_invalid_characters_KO': 'Caracteres invalidos en correo',
	'alumnograduacion_titulacion_format_KO': 'Formato de titulacion no valido',
	'alumnograduacion_telefono_invalid_characters_KO': 'Caracteres invalidos en telefono',
	'alumnograduacion_fotoacto_invalid_characters_KO': 'Nombre de fichero invalido',
	'alumnograduacion_telefono_max_size_KO': 'Tamano maximo telefono excedido',
	'alumnograduacion_direccion_empty_KO': 'El campo no puede estar vacio',
	'alumnograduacion_login_only_spaces_KO': 'No puede contener solo espacios',
	'alumnograduacion_login_numbers_KO': 'Solo puede contener caracteres alfabeticos',
	'alumnograduacion_password_only_spaces_KO': 'No puede contener solo espacios',
	'alumnograduacion_password_numbers_KO': 'Solo puede contener caracteres alfabeticos',
	'alumnograduacion_nombre_only_spaces_KO': 'No puede contener solo espacios',
	'alumnograduacion_nombre_numbers_KO': 'Solo puede contener caracteres alfabeticos',
	'alumnograduacion_apellidos_numbers_KO': 'Solo puede contener caracteres alfabeticos',
	'alumnograduacion_dni_no_letter_KO': 'Falta la letra',
	'alumnograduacion_telefono_hyphens_KO': 'No puede contener guiones',
	'alumnograduacion_nombre_format_KO': 'Formato de nombre no valido',
	'CodigoA': 'Codigo',
	'FicheropdfA': 'Fichero PDF',
	'id_site': 'id_site',
	'site_latitud': 'Latitud',
	'site_longitud': 'Longitud',
	'site_altitude': 'Altitud',
	'site_locality': 'Localidad',
	'site_provider_login': 'Provider login',
	'site_north_photo': 'foto norte',
	'site_south_photo': 'foto sur',
	'site_east_photo': 'foto este',
	'site_west_photo': 'foto oeste',
	'msg_latitud_-90_aceptada': 'Latitud -90 aceptada',
	'msg_latitud_90_aceptada': 'Latitud 90 aceptada',
	'msg_longitud_-180_aceptada': 'Longitud -180 aceptada',
	'msg_longitud_180_aceptada': 'Longitud 180 aceptada',
	'empty_file': 'Archivo vacio',
	'valid_file': 'Fichero valido',
	'invalid_format_file': 'Formato invalido',
	'oversized_file': 'Fichero demasiado grande',
	'invalid_name_file': 'Nombre de fichero invalido',

	// Mensajes anadidos: traducciones naturales en espanol
	'alumnograduacion_login_min_size_KO': 'El login es demasiado corto (minimo 4 caracteres)',
	'alumnograduacion_login_too_short_KO': 'El login es demasiado corto (minimo 4 caracteres)',
	'alumnograduacion_login_max_size_KO': 'El login es demasiado largo (maximo 15 caracteres)',
	'alumnograduacion_login_format_KO': 'El login solo puede contener caracteres alfabeticos sin acentos ni n',
	'alumnograduacion_login_accented_KO': 'El login no puede contener caracteres acentuados',
	'alumnograduacion_password_min_size_KO': 'La contrasena debe tener al menos 8 caracteres',
	'alumnograduacion_password_max_size_KO': 'La contrasena no puede exceder 64 caracteres',
	'alumnograduacion_password_alpha_KO': 'La contrasena solo puede contener caracteres alfabeticos y espacios',
	'alumnograduacion_nombre_min_size_KO': 'El nombre debe tener al menos 2 caracteres',
	'alumnograduacion_nombre_max_size_KO': 'El nombre no puede exceder 25 caracteres',
	'alumnograduacion_apellidos_alpha_KO': 'Los apellidos solo pueden contener letras, espacios y acentos',
	'alumnograduacion_apellidos_min_size_KO': 'Los apellidos deben tener al menos 2 caracteres',
	'alumnograduacion_apellidos_max_size_KO': 'Los apellidos no pueden exceder 35 caracteres',
	'alumnograduacion_dni_min_size_KO': 'El DNI debe tener 9 caracteres',
	'alumnograduacion_dni_num_KO': 'El DNI debe contener numeros correctamente',
	'alumnograduacion_telefono_min_size_KO': 'El telefono debe tener 9 digitos',
	'alumnograduacion_telefono_num_KO': 'El telefono solo puede contener digitos',
	'alumnograduacion_email_max_size_KO': 'El correo electronico no puede exceder 100 caracteres',
	'alumnograduacion_direccion_min_size_KO': 'La direccion no puede estar vacia',
	'alumnograduacion_email_min_size_KO': 'El correo electronico debe tener al menos 5 caracteres',
	'alumnograduacion_email_format_KO': 'El correo electronico tiene un formato invalido',
	'alumnograduacion_login_empty_KO': 'El login no puede ser solo espacios',
	'alumnograduacion_login_spaces_KO': 'El login no puede contener espacios',
	'alumnograduacion_login_num_KO': 'El login no puede contener numeros',
	'alumnograduacion_login_symbols_KO': 'El login no puede contener simbolos',
	'alumnograduacion_nombre_empty_KO': 'El nombre no puede ser solo espacios',
	'alumnograduacion_dni_spaces_KO': 'El DNI no puede contener espacios',
	'alumnograduacion_email_no_at_KO': 'El correo debe contener @',
	'alumnograduacion_email_no_domain_KO': 'El correo electronico debe contener un dominio valido',
	'alumnograduacion_email_multiple_at_KO': 'El correo electronico no puede contener mas de una @',
	'alumnograduacion_fotoacto_spaces_KO': 'El nombre del fichero no puede contener espacios',
	'alumnograduacion_fotoacto_no_extension_KO': 'El fichero debe incluir una extension valida',
	'alumnograduacion_login_too_long_KO': 'El login es demasiado largo (maximo 15 caracteres)',
	'alumnograduacion_password_invalid_characters_KO': 'La contrasena contiene caracteres no permitidos',
	'alumnograduacion_nombre_invalid_characters_KO': 'El nombre contiene caracteres no permitidos',
	'alumnograduacion_apellidos_invalid_characters_KO': 'Los apellidos contienen caracteres no permitidos',
	'alumnograduacion_dni_format_KO': 'Formato de NIF/NIE incorrecto',
	'alumnograduacion_direccion_invalid_characters_KO': 'La direccion contiene caracteres no permitidos',
	'alumnograduacion_password_format_KO': 'Formato de contrasena no valido',
	'alumnograduacion_apellidos_format_KO': 'Formato de apellidos no valido',
	'alumnograduacion_telefono_format_KO': 'Formato de telefono incorrecto',
	'alumnograduacion_direccion_format_KO': 'Formato de direccion no valido',
	'id_site_not_numeric_KO': 'El id_site debe ser numerico',
	'site_latitud_range_KO': 'La latitud debe estar en el rango [-90, 90]',
	'site_longitud_range_KO': 'La longitud debe estar en el rango [-180, 180]',
	'site_altitude_not_numeric_KO': 'La altitud debe ser un numero entero',
	'site_locality_maxlen_KO': 'La localidad no puede exceder 40 caracteres',
	'site_provider_login_empty_KO': 'El login del proveedor no puede estar vacio',
	'site_north_photo_type_KO': 'Solo se permiten imagenes jpg, jpeg o png',
	'site_south_photo_name_KO': 'El nombre del fichero no puede contener espacios',
	'site_east_photo_type_KO': 'Solo se permiten imagenes jpg, jpeg o png',
	'site_east_photo_name_KO': 'El nombre del fichero no puede contener espacios',
	'site_west_photo_type_KO': 'Solo se permiten imagenes jpg, jpeg o png',
	'site_west_photo_no_extension_KO': 'El fichero debe incluir una extension valida',
	'site_provider_login_maxlen_KO': 'El login del proveedor no puede exceder 30 caracteres',
	'alumnograduacion_fotoacto_empty_KO': 'El fichero no puede estar vacio',
	'alumnograduacion_fotoacto_format_KO': 'Formato de fichero no permitido',
	'alumnograduacion_fotoacto_size_KO': 'El fichero es demasiado grande',
	'site_north_photo_empty_KO': 'El fichero no puede estar vacio',
	'site_north_photo_size_KO': 'El fichero es demasiado grande'


};